"""initial schema multi-tenant

Revision ID: 01f435f74091
Revises: 
Create Date: 2026-03-21 09:11:37.225112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01f435f74091'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('apellido', sa.String(length=150), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=False),
    sa.CheckConstraint("tipo IN ('gym', 'usuario', 'admin')", name='ck_usuario_tipo'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_cliente', sa.String(length=36), nullable=False),
    sa.Column('gym_id', sa.String(length=36), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('edad', sa.Integer(), nullable=True),
    sa.Column('sexo', sa.String(length=10), nullable=True),
    sa.Column('peso_kg', sa.Float(), nullable=True),
    sa.Column('estatura_cm', sa.Float(), nullable=True),
    sa.Column('grasa_corporal_pct', sa.Float(), nullable=True),
    sa.Column('masa_magra_kg', sa.Float(), nullable=True),
    sa.Column('nivel_actividad', sa.String(length=30), nullable=True),
    sa.Column('objetivo', sa.String(length=30), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.Column('ultimo_plan', sa.DateTime(), nullable=True),
    sa.Column('total_planes_generados', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('plantilla_tipo', sa.String(length=30), nullable=True),
    sa.CheckConstraint("sexo IN ('M', 'F', 'Otro') OR sexo IS NULL", name='ck_cliente_sexo'),
    sa.ForeignKeyConstraint(['gym_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_cliente')
    )
    op.create_index('ix_clientes_gym_activo', 'clientes', ['gym_id', 'activo'], unique=False)
    op.create_index(op.f('ix_clientes_gym_id'), 'clientes', ['gym_id'], unique=False)
    op.create_index('ix_clientes_gym_nombre', 'clientes', ['gym_id', 'nombre'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('expires_at', sa.Float(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('jti')
    )
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('planes_generados',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_cliente', sa.String(length=36), nullable=False),
    sa.Column('gym_id', sa.String(length=36), nullable=False),
    sa.Column('fecha_generacion', sa.DateTime(), nullable=True),
    sa.Column('tmb', sa.Float(), nullable=True),
    sa.Column('get_total', sa.Float(), nullable=True),
    sa.Column('kcal_objetivo', sa.Float(), nullable=True),
    sa.Column('kcal_real', sa.Float(), nullable=True),
    sa.Column('proteina_g', sa.Float(), nullable=True),
    sa.Column('carbs_g', sa.Float(), nullable=True),
    sa.Column('grasa_g', sa.Float(), nullable=True),
    sa.Column('objetivo', sa.String(length=30), nullable=True),
    sa.Column('nivel_actividad', sa.String(length=30), nullable=True),
    sa.Column('ruta_pdf', sa.String(length=500), nullable=True),
    sa.Column('peso_en_momento', sa.Float(), nullable=True),
    sa.Column('grasa_en_momento', sa.Float(), nullable=True),
    sa.Column('desviacion_maxima_pct', sa.Float(), nullable=True),
    sa.Column('plantilla_tipo', sa.String(length=30), nullable=True),
    sa.Column('tipo_plan', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['gym_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_cliente'], ['clientes.id_cliente'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_planes_generados_gym_id'), 'planes_generados', ['gym_id'], unique=False)
    op.create_index(op.f('ix_planes_generados_id_cliente'), 'planes_generados', ['id_cliente'], unique=False)
    op.create_index('ix_planes_gym_fecha', 'planes_generados', ['gym_id', 'fecha_generacion'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_planes_gym_fecha', table_name='planes_generados')
    op.drop_index(op.f('ix_planes_generados_id_cliente'), table_name='planes_generados')
    op.drop_index(op.f('ix_planes_generados_gym_id'), table_name='planes_generados')
    op.drop_table('planes_generados')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('ix_clientes_gym_nombre', table_name='clientes')
    op.drop_index(op.f('ix_clientes_gym_id'), table_name='clientes')
    op.drop_index('ix_clientes_gym_activo', table_name='clientes')
    op.drop_table('clientes')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
